/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

#include<stdio.h>
#include<stdlib.h>
#define MAX 4000000

int main() {
  long long sum=0;
  long long f1=1,f2=1,fib,mod=2;
  
  while(f1<MAX){
      fib=f1+f2;
      if(fib%mod==0)
        sum+=fib;
      f1=f2;
      f2=fib;
  }//while
  printf("%ld",sum);
  return 0;
}

/*
output:
4613732
*/
